- name: Install Horizon packages
  apt:
    name:
      - openstack-dashboard
    state: present

- name: Configure Apache for Horizon
  template:
    src: openstack-dashboard.conf.j2
    dest: /etc/apache2/sites-available/openstack-dashboard.conf

- name: Configure Horizon settings
  template:
    src: local_settings.py.j2
    dest: /etc/openstack-dashboard/local_settings.py

- name: Restart Apache
  service:
    name: apache2
    state: restarted
